<?php

$toshiba1name = "";
$toshiba2name = "";
$toshiba3name = "";
$toshiba4name = "";
$toshiba5name = "";
$lg1name = "";
$lg2name = "";
$lg3name = "";
$lg4name = "";
$bosch1name ="";
$bosch2name ="";
$bosch3name ="";
$panasonic1name ="";
$panasonic2name ="";
$samsungwm1name ="";
$samsungwm2name ="";
$samsungtv1name ="";
$samsungtv2name ="";
$sonytv1name ="";
$sonytv2name ="";
$lgtv1name ="";
$prismtv1name ="";
$prismtv2name ="";
$xiaomitv1name ="";
$xiaomitv2name ="";
$sharptv1name ="";
$tarrynname = "";

$toshiba1price = "";
$toshiba2price = "";
$toshiba3price = "";
$toshiba5price = "";
$lg1price ="";
$lg2price ="";
$lg3price ="";
$lg4price ="";
$bosch1price ="";
$bosch2price ="";
$bosch3price ="";
$panasonic1price ="";
$panasonic2price ="";
$samsungwm1price ="";
$samsungwm2price ="";
$samsungtv1price ="";
$samsungtv2price ="";
$sonytv1price ="";
$sonytv2price ="";
$lgtv1price ="";
$prismtv1price ="";
$prismtv2price ="";
$xiaomitv1price ="";
$xiaomitv2price ="";
$sharptv1price ="";
$tarrynprice = "";


$conn = mysqli_connect("localhost", "X34110222", "X34110222", "X34110222");


if($conn === false){
    die("ERROR: Could not connect. " . mysqli_connect_error());
}

// Product name SQL Query

$toshiba1NameSql = 'select productName from Products where serialNumber = "1"';
$toshiba2NameSql = 'select productName from Products where serialNumber = "2"';
$toshiba3NameSql = 'select productName from Products where serialNumber = "3"';
$toshiba4NameSql = 'select productName from Products where serialNumber = "4"';
$toshiba5NameSql = 'select productName from Products where serialNumber = "5"';
$lg1NameSql = 'select productName from Products where serialNumber = "6"';
$lg2NameSql = 'select productName from Products where serialNumber = "7"';
$lg3NameSql = 'select productName from Products where serialNumber = "8"';
$lg4NameSql = 'select productName from Products where serialNumber = "9"';
$bosch1NameSql = 'select productName from Products where serialNumber = "10"';
$bosch2NameSql = 'select productName from Products where serialNumber = "11"';
$bosch3NameSql = 'select productName from Products where serialNumber = "91"';
$panasonic1NameSql = 'select productName from Products where serialNumber = "12"';
$panasonic2NameSql = 'select productName from Products where serialNumber = "13"';
$samsungwm1NameSql = 'select productName from Products where serialNumber = "14"';
$samsungwm2NameSql = 'select productName from Products where serialNumber = "15"';
$samsungtv1NameSql = 'select productName from Products where serialNumber = "16"';
$samsungtv2NameSql = 'select productName from Products where serialNumber = "17"';
$sonytv1NameSql = 'select productName from Products where serialNumber = "18"';
$sonytv2NameSql = 'select productName from Products where serialNumber = "19"';
$lgtv1NameSql = 'select productName from Products where serialNumber = "20"';
$prismtv1NameSql = 'select productName from Products where serialNumber = "21"';
$prismtv2NameSql = 'select productName from Products where serialNumber = "22"';
$xiaomitv1NameSql = 'select productName from Products where serialNumber = "23"';
$xiaomitv2NameSql = 'select productName from Products where serialNumber = "24"';
$sharptv1NameSql = 'select productName from Products where serialNumber = "25"';
$tarrynNameSql = 'select productName from Products where serialNumber = "70"';

$toshiba1PriceSql = 'select price from Products where serialNumber = "1"';
$toshiba2PriceSql = 'select price from Products where serialNumber = "2"';
$toshiba3PriceSql = 'select price from Products where serialNumber = "3"';
$toshiba4PriceSql = 'select price from Products where serialNumber = "4"';
$toshiba5PriceSql = 'select price from Products where serialNumber = "5"';
$lg1PriceSql = 'select price from Products where serialNumber = "6"';
$lg2PriceSql = 'select price from Products where serialNumber = "7"';
$lg3PriceSql = 'select price from Products where serialNumber = "8"';
$lg4PriceSql = 'select price from Products where serialNumber = "9"';
$bosch1PriceSql = 'select price from Products where serialNumber = "10"';
$bosch2PriceSql = 'select price from Products where serialNumber = "11"';
$bosch3PriceSql = 'select price from Products where serialNumber = "91"';
$panasonic1PriceSql = 'select price from Products where serialNumber = "12"';
$panasonic2PriceSql = 'select price from Products where serialNumber = "13"';
$samsungwm1PriceSql = 'select price from Products where serialNumber = "14"';
$samsungwm2PriceSql = 'select price from Products where serialNumber = "15"';
$samsungtv1PriceSql = 'select price from Products where serialNumber = "16"';
$samsungtv2PriceSql = 'select price from Products where serialNumber = "17"';
$sonytv1PriceSql = 'select price from Products where serialNumber = "18"';
$sonytv2PriceSql = 'select price from Products where serialNumber = "19"';
$lgtv1PriceSql = 'select price from Products where serialNumber = "20"';
$prismtv1PriceSql = 'select price from Products where serialNumber = "21"';
$prismtv2PriceSql = 'select price from Products where serialNumber = "22"';
$xiaomitv1PriceSql = 'select price from Products where serialNumber = "23"';
$xiaomitv2PriceSql = 'select price from Products where serialNumber = "24"';
$sharptv1PriceSql = 'select price from Products where serialNumber = "25"';
$tarrynPriceSql = 'select price from Products where serialNumber = "70"';


$toshiba1Name = mysqli_query($conn, $toshiba1NameSql) or trigger_error("Query Failed! SQL: $toshiba1NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$toshiba2Name = mysqli_query($conn, $toshiba2NameSql) or trigger_error("Query Failed! SQL: $toshiba2NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$toshiba3Name = mysqli_query($conn, $toshiba3NameSql ) or trigger_error("Query Failed! SQL: $toshiba3NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$toshiba4Name = mysqli_query($conn, $toshiba4NameSql ) or trigger_error("Query Failed! SQL: $toshiba4NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$toshiba5Name = mysqli_query($conn, $toshiba5NameSql ) or trigger_error("Query Failed! SQL: $toshiba5NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$lg1Name = mysqli_query($conn, $lg1NameSql ) or trigger_error("Query Failed! SQL: $lg1NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$lg2Name = mysqli_query($conn, $lg2NameSql ) or trigger_error("Query Failed! SQL: $lg2NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$lg3Name = mysqli_query($conn, $lg3NameSql ) or trigger_error("Query Failed! SQL: $lg3NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$lg4Name = mysqli_query($conn, $lg4NameSql ) or trigger_error("Query Failed! SQL: $lg4NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$bosch1Name = mysqli_query($conn, $bosch1NameSql ) or trigger_error("Query Failed! SQL: $bosch1NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$bosch2Name = mysqli_query($conn, $bosch2NameSql ) or trigger_error("Query Failed! SQL: $bosch2NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$bosch3Name = mysqli_query($conn, $bosch3NameSql ) or trigger_error("Query Failed! SQL: $bosch3NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$panasonic1Name = mysqli_query($conn, $panasonic1NameSql ) or trigger_error("Query Failed! SQL: $panasonic1NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$panasonic2Name = mysqli_query($conn, $panasonic2NameSql ) or trigger_error("Query Failed! SQL: $panasonic2NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$samsungwm1Name = mysqli_query($conn, $samsungwm1NameSql ) or trigger_error("Query Failed! SQL: $samsungwm1NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$samsungwm2Name = mysqli_query($conn, $samsungwm2NameSql ) or trigger_error("Query Failed! SQL: $samsungwm2NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$samsungtv1Name = mysqli_query($conn, $samsungtv1NameSql ) or trigger_error("Query Failed! SQL: $samsungtv1NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$samsungtv2Name = mysqli_query($conn, $samsungtv2NameSql ) or trigger_error("Query Failed! SQL: $samsungtv2NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$sonytv1Name = mysqli_query($conn, $sonytv1NameSql ) or trigger_error("Query Failed! SQL: $sonytv1NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$sonytv2Name = mysqli_query($conn, $sonytv2NameSql ) or trigger_error("Query Failed! SQL: $sonytv2NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$lgtv1Name = mysqli_query($conn, $lgtv1NameSql ) or trigger_error("Query Failed! SQL: $lgtv1NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$prismtv1Name = mysqli_query($conn, $prismtv1NameSql ) or trigger_error("Query Failed! SQL: $prismtv1NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$prismtv2Name = mysqli_query($conn, $prismtv2NameSql ) or trigger_error("Query Failed! SQL: $prismtv2NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$xiaomitv1Name = mysqli_query($conn, $xiaomitv1NameSql ) or trigger_error("Query Failed! SQL: $xiaomitv1NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$xiaomitv2Name = mysqli_query($conn, $xiaomitv2NameSql ) or trigger_error("Query Failed! SQL: $xiaomitv2NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$sharptv1Name = mysqli_query($conn, $sharptv1NameSql ) or trigger_error("Query Failed! SQL: $sharptv1NameSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$tarrynName = mysqli_query($conn, $tarrynNameSql) or trigger_error("Query Failed! SQL: $tarrynNameSql - Error: ".mysqli_error($conn), E_USER_ERROR);

$toshiba1Price = mysqli_query($conn, $toshiba1PriceSql) or trigger_error("Query Failed! SQL: $toshiba1PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$toshiba2Price = mysqli_query($conn, $toshiba2PriceSql ) or trigger_error("Query Failed! SQL: $toshiba2PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$toshiba3Price = mysqli_query($conn, $toshiba3PriceSql ) or trigger_error("Query Failed! SQL: $toshiba3PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$toshiba4Price = mysqli_query($conn, $toshiba3PriceSql ) or trigger_error("Query Failed! SQL: $toshiba4PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$toshiba5Price = mysqli_query($conn, $toshiba3PriceSql ) or trigger_error("Query Failed! SQL: $toshiba5PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$lg1Price = mysqli_query($conn, $lg1PriceSql) or trigger_error("Query Failed! SQL: $lg1PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$lg2Price = mysqli_query($conn, $lg2PriceSql) or trigger_error("Query Failed! SQL: $lg2PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$lg3Price = mysqli_query($conn, $lg3PriceSql) or trigger_error("Query Failed! SQL: $lg3PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$lg4Price = mysqli_query($conn, $lg4PriceSql) or trigger_error("Query Failed! SQL: $lg4PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$bosch1Price = mysqli_query($conn, $bosch1PriceSql ) or trigger_error("Query Failed! SQL: $bosch1PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$bosch2Price = mysqli_query($conn, $bosch2PriceSql ) or trigger_error("Query Failed! SQL: $bosch2PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$bosch3Price = mysqli_query($conn, $bosch3PriceSql ) or trigger_error("Query Failed! SQL: $bosch3PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$panasonic1Price = mysqli_query($conn, $panasonic1PriceSql ) or trigger_error("Query Failed! SQL: $panasonic1PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$panasonic2Price = mysqli_query($conn, $panasonic1PriceSql ) or trigger_error("Query Failed! SQL: $panasonic2PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$samsungwm1Price = mysqli_query($conn, $samsungwm1PriceSql ) or trigger_error("Query Failed! SQL: $samsungwm1PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$samsungwm2Price = mysqli_query($conn, $samsungwm2PriceSql ) or trigger_error("Query Failed! SQL: $samsungwm2PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$samsungtv1Price = mysqli_query($conn, $samsungtv1PriceSql ) or trigger_error("Query Failed! SQL: $samsungtv1PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$samsungtv2Price = mysqli_query($conn, $samsungtv2PriceSql ) or trigger_error("Query Failed! SQL: $samsungtv2PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$sonytv1Price = mysqli_query($conn, $sonytv1PriceSql ) or trigger_error("Query Failed! SQL: $sonytv1PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$sonytv2Price = mysqli_query($conn, $sonytv2PriceSql ) or trigger_error("Query Failed! SQL: $sonytv2PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$lgtv1Price = mysqli_query($conn, $lgtv1PriceSql ) or trigger_error("Query Failed! SQL: $lgtv1PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$prismtv1Price = mysqli_query($conn, $prismtv1PriceSql ) or trigger_error("Query Failed! SQL: $prismtv1PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$prismtv2Price = mysqli_query($conn, $prismtv2PriceSql ) or trigger_error("Query Failed! SQL: $prismtv2PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$xiaomitv1Price = mysqli_query($conn, $xiaomitv1PriceSql ) or trigger_error("Query Failed! SQL: $xiaomitv1PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$xiaomitv2Price = mysqli_query($conn, $xiaomitv2PriceSql ) or trigger_error("Query Failed! SQL: $xiaomitv2PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$sharptv1Price = mysqli_query($conn, $sharptv1PriceSql ) or trigger_error("Query Failed! SQL: $sharptv1PriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);
$tarrynPrice = mysqli_query($conn, $tarrynPriceSql) or trigger_error("Query Failed! SQL: $tarrynPriceSql - Error: ".mysqli_error($conn), E_USER_ERROR);

mysqli_close($conn);


$toshiba1name = $toshiba1Name ->fetch_array()['productName'];
$toshiba2name = $toshiba2Name ->fetch_array()['productName'];
$toshiba3name = $toshiba3Name ->fetch_array()['productName'];
$toshiba4name = $toshiba4Name ->fetch_array()['productName'];
$toshiba5name = $toshiba5Name ->fetch_array()['productName'];
$lg1name = $lg1Name ->fetch_array()['productName'];
$lg2name = $lg2Name ->fetch_array()['productName'];
$lg3name = $lg3Name ->fetch_array()['productName'];
$lg4name = $lg4Name ->fetch_array()['productName'];
$bosch1name = $bosch1Name ->fetch_array()['productName'];
$bosch2name = $bosch2Name ->fetch_array()['productName'];
$bosch3name = $bosch3Name ->fetch_array()['productName'];
$panasonic1name = $panasonic1Name ->fetch_array()['productName'];
$panasonic2name = $panasonic2Name ->fetch_array()['productName'];
$samsungwm1name = $samsungwm1Name ->fetch_array()['productName'];
$samsungwm2name = $samsungwm2Name ->fetch_array()['productName'];
$samsungtv1name = $samsungtv1Name ->fetch_array()['productName'];
$samsungtv2name = $samsungtv2Name ->fetch_array()['productName'];
$sonytv1name = $sonytv1Name ->fetch_array()['productName'];
$sonytv2name = $sonytv2Name ->fetch_array()['productName'];
$lgtv1name = $lgtv1Name ->fetch_array()['productName'];
$prismtv1name = $prismtv1Name ->fetch_array()['productName'];
$prismtv2name = $prismtv2Name ->fetch_array()['productName'];
$xiaomitv1name = $xiaomitv1Name ->fetch_array()['productName'];
$xiaomitv2name = $xiaomitv2Name ->fetch_array()['productName'];
$sharptv1name = $sharptv1Name ->fetch_array()['productName'];
$tarrynname = $tarrynName ->fetch_array()['productName'];

$toshiba1price = $toshiba1Price ->fetch_array()['price'];
$toshiba2price = $toshiba2Price ->fetch_array()['price'];
$toshiba3price = $toshiba3Price ->fetch_array()['price'];
$toshiba4price = $toshiba4Price ->fetch_array()['price'];
$toshiba5price = $toshiba5Price ->fetch_array()['price'];
$lg1price = $lg1Price ->fetch_array()['price'];
$lg2price = $lg2Price ->fetch_array()['price'];
$lg3price = $lg3Price ->fetch_array()['price'];
$lg4price = $lg4Price ->fetch_array()['price'];
$bosch1price = $bosch1Price ->fetch_array()['price'];
$bosch2price = $bosch2Price ->fetch_array()['price'];
$bosch3price = $bosch3Price ->fetch_array()['price'];
$panasonic1price = $panasonic1Price ->fetch_array()['price'];
$panasonic2price = $panasonic2Price ->fetch_array()['price'];
$samsungwm1price = $samsungwm1Price ->fetch_array()['price'];
$samsungwm2price = $samsungwm2Price ->fetch_array()['price'];
$samsungtv1price = $samsungtv1Price ->fetch_array()['price'];
$samsungtv2price = $samsungtv2Price ->fetch_array()['price'];
$sonytv1price = $sonytv1Price ->fetch_array()['price'];
$sonytv2price = $sonytv2Price ->fetch_array()['price'];
$lgtv1price = $lgtv1Price ->fetch_array()['price'];
$prismtv1price = $prismtv1Price ->fetch_array()['price'];
$prismtv2price = $prismtv2Price ->fetch_array()['price'];
$xiaomitv1price = $xiaomitv1Price ->fetch_array()['price'];
$xiaomitv2price = $xiaomitv2Price ->fetch_array()['price'];
$sharptv1price = $sharptv1Price ->fetch_array()['price'];
$tarrynprice = $tarrynPrice ->fetch_array()['price'];

$reply->toshiba1Name = $toshiba1name;
$reply->toshiba2Name = $toshiba2name;
$reply->toshiba3Name = $toshiba3name;
$reply->toshiba4Name = $toshiba4name;
$reply->toshiba5Name = $toshiba5name;
$reply->lg1Name = $lg1name;
$reply->lg2Name = $lg2name;
$reply->lg3Name = $lg3name;
$reply->lg4Name = $lg4name;
$reply->bosch1Name = $bosch1name;
$reply->bosch2Name = $bosch2name;
$reply->bosch3Name = $bosch3name;
$reply->panasonic1Name = $panasonic1name;
$reply->panasonic2Name = $panasonic2name;
$reply->samsungwm1Name = $samsungwm1name;
$reply->samsungwm2Name = $samsungwm2name;
$reply->samsungtv1Name = $samsungtv1name;
$reply->samsungtv2Name = $samsungtv2name;
$reply->sonytv1Name = $sonytv1name;
$reply->sonytv2Name = $sonytv2name;
$reply->lgtv1Name = $lgtv1name;
$reply->prismtv1Name = $prismtv1name;
$reply->prismtv2Name = $prismtv2name;
$reply->xiaomitv1Name = $xiaomitv1name;
$reply->xiaomitv2Name = $xiaomitv2name;
$reply->sharptv1Name = $sharptv1name;
$reply->tarrynName = $tarrynname;

$reply->toshiba1Price = $toshiba1price;
$reply->toshiba2Price = $toshiba2price;
$reply->toshiba3Price = $toshiba3price;
$reply->toshiba4Price = $toshiba4price;
$reply->toshiba5Price = $toshiba5price;
$reply->lg1Price = $lg1price;
$reply->lg2Price = $lg2price;
$reply->lg3Price = $lg3price;
$reply->lg4Price = $lg4price;
$reply->bosch1Price = $bosch1price;
$reply->bosch2Price = $bosch2price;
$reply->bosch3Price = $bosch3price;
$reply->panasonic1Price = $panasonic1price;
$reply->panasonic2Price = $panasonic2price;
$reply->samsungwm1Price = $samsungwm1price;
$reply->samsungwm2Price = $samsungwm2price;
$reply->samsungtv1Price = $samsungtv1price;
$reply->samsungtv2Price = $samsungtv2price;
$reply->sonytv1Price = $sonytv1price;
$reply->sonytv2Price = $sonytv2price;
$reply->lgtv1Price = $lgtv1price;
$reply->prismtv1Price = $prismtv1price;
$reply->prismtv2Price = $prismtv2price;
$reply->xiaomitv1Price = $xiaomitv1price;
$reply->xiaomitv2Price = $xiaomitv2price;
$reply->sharptv1Price = $sharptv1price;
$jsonReply = json_encode($reply);

header('Content-Type: application/json');
echo $jsonReply;

?>